imagePullPolicy: IfNotPresent

# Node labels for pod assignment
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

planqstats:
  image:
    server:
      repository: gcr.io/celo-testnet/planqstats-server
      tag: latest
    frontend:
      repository: gcr.io/celo-testnet/planqstats-frontend
      tag: latest
  service:
    type: NodePort
  trusted_addresses: []
  banned_addresses: []

domain:
  name: planq-testnet

ingressClassName: nginx

resources:
  server:
    requests:
      cpu: 15m
      memory: 110Mi
    limits: {}
  frontend:
    requests:
      cpu: 1m
      memory: 5Mi
    limits: {}
