[profile.default]
src = 'contracts'
out = 'out'
test = 'test-sol'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    'openzeppelin-solidity/=lib/openzeppelin-contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    'forge-std/=lib/planq-foundry/lib/forge-std/src/',
    'ds-test/=lib/planq-foundry/lib/forge-std/lib/ds-test/src/',
    '@summa-tx/memview.sol/=lib/memview.sol',
    '@astonic-core/=lib/astonic-core',
    '@openzeppelin/contracts8/=lib/openzeppelin-contracts8/contracts/',
    '@test-sol/=test-sol/',
    '@migrations-sol/=migrations_sol/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
]
no_match_test = "skip"
# `BLS12Passthrough.sol` is excluded, because it's tested in the celo-blockain repo as
# described here: https://github.com/celo-org/celo-monorepo/pull/10240
# `Random.sol` is excluded, but I'm not sure why. It was already excluded so I'm leaving it here.
no_match_path = "*test/{BLS12Passthrough.sol,RandomTest.sol}"
fs_permissions = [{ access = "read", path = "./out"}, { access = "read", path = "./migrations_sol/migrationsConfig.json"}, { access = "read", path = "./governanceConstitution.json"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
