[default]
src = 'contracts'
out = 'out'
test = 'test-sol'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    'openzeppelin-solidity/=lib/openzeppelin-contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    'forge-std/=lib/planq-foundry/lib/forge-std/src/',
    'ds-test/=lib/planq-foundry/lib/forge-std/lib/ds-test/src/',
    'planq-foundry/=lib/planq-foundry/src/',
    '@summa-tx/memview.sol/=lib/memview.sol'
]

no_match_contract = "RandomTest"
no_match_path = "contracts/common/libraries/test/BLS12Passthrough.sol"  # tested from planq-blockain repo

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
