apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.environment }}-tracer-tool
  labels:
    app: tracer-tool
    chart: tracer-tool
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: tracer-tool
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      replicas: 1
      template:
        spec:
          containers:
          - name: tracer-tool
            image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            command: ["/bin/bash"]
            args: ["-c", '{{ .Files.Get "scripts/run.sh" }}', "{{ .Values.environment }}"]
            resources:
              requests:
                memory: 1G
                cpu: 300m
            volumeMounts:
            - name: starting-files
              mountPath: /root
            - name: geth-config
              mountPath: /geth
          volumes:
          - name: starting-files
            configMap:
              name: {{ .Values.environment }}-tracer-tool-config      
          - name: geth-config
            configMap:
              name: {{ .Values.environment }}-geth-config
          restartPolicy: Never
