apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}-planqstats-server
  labels:
    app: planqstats
    chart: planqstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: planqstats-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planqstats
      release: {{ .Release.Name }}
      component: planqstats-server
  template:
    metadata:
      labels:
        app: planqstats
        release: {{ .Release.Name }}
        component: planqstats-server
    spec:
      containers:
      - name: planqstats-server
        image: {{ .Values.planqstats.image.server.repository }}:{{ .Values.planqstats.image.server.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: TRUSTED_ADDRESSES
          value: {{ .Values.planqstats.trusted_addresses }}
        - name: BANNED_ADDRESSES
          value: {{ .Values.planqstats.banned_addresses }}
        - name: RESERVED_ADDRESSES
          value: {{ .Values.planqstats.reserved_addresses }}
        - name: JSONRPC
          value: {{ .Values.planqstats.jsonrpc }}
        command:
        - /bin/sh
        - -c
        args:
        - |
          sed -i "s%###NETWORK_NAME###%{{ .Values.planqstats.network_name }}%g" /planqstats-server/dist/js/netstats.min.js
          sed -i "s%###BLOCKSCOUT_URL###%{{ .Values.planqstats.blockscout_url }}%g" /planqstats-server/dist/js/netstats.min.js
          exec npm start
        ports:
        - name: http
          containerPort: 3000
      {{- with .Values.resources.server }}
        resources:
          {{- toYaml . | nindent 10 }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
