apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-planqstats-frontend
  labels:
    app: planqstats
    chart: planqstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: planqstats-frontend
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: {{ default "nginx" .Values.ingressClassName }}
  tls:
  - hosts:
    - {{ .Release.Namespace }}-planqstats.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Namespace }}-planqstats-frontend-tls
  rules:
  - host: {{ .Release.Namespace }}-planqstats.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Namespace }}-planqstats-frontend
            port: 
              number: 80
