kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}-planqstats-server
  labels:
    app: planqstats
    chart: planqstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: planqstats-server
spec:
  selector:
    app: planqstats
    release: {{ .Release.Name }}
    component: planqstats-server
  type: {{ .Values.planqstats.service.type }}
  ports:
  - port: 80
    targetPort: http
