apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}-planqstats-frontend
  labels:
    app: planqstats
    chart: planqstats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: planqstats-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planqstats
      release: {{ .Release.Name }}
      component: planqstats-frontend
  template:
    metadata:
      labels:
        app: planqstats
        release: {{ .Release.Name }}
        component: planqstats-frontend
    spec:
      containers:
      - name: planqstats-frontend
        image: {{ .Values.planqstats.image.frontend.repository }}:{{ .Values.planqstats.image.frontend.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: ETHSTATS_SERVICE
          value: https://{{ .Release.Namespace }}-planqstats-server.{{ .Values.domain.name }}.org
        - name: BLOCKSCOUT_URL
          value: https://{{ .Release.Namespace }}-blockscout.{{ .Values.domain.name }}.org
        - name: SUBMENU_BLOCKSCOUT
          value: https://{{ .Release.Namespace }}-blockscout.{{ .Values.domain.name }}.org
        - name: GRAPHQL_BLOCKSCOUT_URL
          value: https://{{ .Release.Namespace }}-blockscout.{{ .Values.domain.name }}.org/graphiql
        command:
        - /bin/sh
        - -c
        args:
        - |
          /var/www/scripts/set-env-variables.js /var/www/app
          ngsw-config /var/www/app/ /var/www/ngsw-config.json
          exec nginx -g "daemon off;"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      {{- with .Values.resources.frontend }}
        resources:
          {{- toYaml . | nindent 10 }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
