steps:

# Unshallow clone
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']

# build docker image for google container registry
- name: gcr.io/kaniko-project/executor:latest
  args: [
    "--dockerfile=dockerfiles/monorepo/Dockerfile.planqtool",
    "--cache=true",
    "--destination=gcr.io/$PROJECT_ID/planq-sdk:planqtool-$COMMIT_SHA"
  ]
  id: Build planqtool docker image
  waitFor: ['-']
timeout: 1000s
