steps:

# Unshallow clone
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']

# build docker image for google container registry
- name: gcr.io/kaniko-project/executor:latest
  args: [
    "--dockerfile=dockerfiles/cli/Dockerfile.cli",
    "--cache=true",
    "--destination=gcr.io/$PROJECT_ID/planqcli:$COMMIT_SHA",
    "--build-arg",
    "planq_env=atlas"
  ]
  id: Build CLI docker image
  waitFor: ['-']
timeout: 1000s
